services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=felipe123
      - POSTGRES_PASSWORD=felipe123
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports: [8080:80]
